import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import SmoothScroll from "@/components/SmoothScroll";
import Announcement from "@/components/Announcement";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The C Theraphy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <SmoothScroll>
            <header>
              <Announcement />
              <Header />
            </header>
              {children}
            <footer>
              <Footer />
            </footer>
          </SmoothScroll>
      </body>
    </html>
  );
}
